name: Golang CI/CD Pipeline

on:
  push:
    branches:
      - master
      - main
      - staging
  pull_request:
    branches:
      - master
      - main
      - staging
    types: [closed]

env:
  PROJECT_NAME: ${{ github.event.repository.name }}
  PORT: 8080
  BRANCH: ${{ github.ref == 'refs/heads/staging' && 'staging' || 'production' }}
  REGISTRY_REPO: antrein

  GCP_REGION: asia-southeast1
  GCP_ZONE: asia-southeast1-a

  AWS_REGION: asia-southeast-1

jobs:
  setup-environment:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.set-env.outputs.IMAGE_TAG }}
      IMAGE_NAME: ${{ steps.set-env.outputs.IMAGE_NAME }}
      BRANCH: ${{ steps.set-env.outputs.BRANCH }}
      SHORT_SHA: ${{ steps.set-env.outputs.SHORT_SHA }}
    steps:
      - name: Set environment variables
        id: set-env
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed -e "s/refs\/heads\///g")
          BRANCH=$(if [ "$BRANCH_NAME" = "staging" ]; then echo "staging"; else echo "production"; fi)
          IMAGE_TAG="$BRANCH:$SHORT_SHA"
          IMAGE_NAME="reyshazni/${{ github.event.repository.name }}-$IMAGE_TAG"
          echo "::set-output name=IMAGE_TAG::$IMAGE_TAG"
          echo "::set-output name=BRANCH::$BRANCH"
          echo "::set-output name=SHORT_SHA::$SHORT_SHA"
          echo "::set-output name=IMAGE_NAME::$IMAGE_NAME"

  dockerize-and-push:
    needs: setup-environment
    environment: ${{ needs.setup-environment.outputs.BRANCH }}
    runs-on: ubuntu-latest
    outputs:
      IMAGE_NAME: ${{ steps.build.outputs.IMAGE_NAME }}
      BRANCH: ${{ steps.set-env.outputs.BRANCH }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Login Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set environment variables
        id: set-env
        run: |
          echo "::set-output name=IMAGE_TAG::${{ needs.setup-environment.outputs.IMAGE_TAG }}"
          echo "::set-output name=BRANCH::${{ needs.setup-environment.outputs.BRANCH }}"

      - name: Create secret
        run: |
          echo '${{ vars.ENV }}' > ./files/secrets/secrets.config.json

      - name: Test secret
        run: |
          cat ./files/secrets/secrets.config.json

      - name: Build and push Docker Image
        id: build
        run: |
          IMAGE_NAME="reyshazni/${{ github.event.repository.name }}:${{ needs.setup-environment.outputs.IMAGE_TAG }}"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
          echo "::set-output name=IMAGE_NAME::$IMAGE_NAME"

  deploy-to-server-gcp:
    needs: dockerize-and-push
    if: vars.CLOUD_PLATFORM == 'gcp'
    runs-on: ubuntu-latest
    environment: ${{ needs.setup-environment.outputs.BRANCH }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Prepare deployment file
        env: 
          IMAGE_NAME: ${{ needs.setup-environment.outputs.IMAGE_NAME }}
          SHORT_SHA: ${{ needs.setup-environment.outputs.SHORT_SHA }}
        run: |
          sed -i "s|<PROJECT_NAME>|${{ env.PROJECT_NAME }}|g" k8s/${{ needs.setup-environment.outputs.BRANCH }}.yml
          sed -i "s|<IMAGE_NAME>|${{ env.IMAGE_NAME }}|g" k8s/${{ needs.setup-environment.outputs.BRANCH }}.yml
          sed -i "s|<VERSION>|${{ env.SHORT_SHA }}|g" k8s/${{ needs.setup-environment.outputs.BRANCH }}.yml
          sed -i "s|<PORT>|${{ env.PORT }}|g" k8s/${{ needs.setup-environment.outputs.BRANCH }}.yml
          cat k8s/${{ needs.setup-environment.outputs.BRANCH }}.yml

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ vars.GCP_SA_KEY }}

      - name: Connect to cluster
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ vars.GCP_CLUSTER_NAME }}
          location: ${{ env.GCP_ZONE }}

      - name: Deploy
        run: |
          kubectl apply -f k8s/${{ needs.setup-environment.outputs.BRANCH }}.yml

      - name: Push YAML to another GitHub repo
        if: github.ref != 'refs/heads/staging'
        env:
          GIT_USER: reyshazni
          GIT_TOKEN: ${{ vars.GIT_PAT }}
          GIT_EMAIL: reyshazni@gmail.com
        run: |
          git config --global user.email ${GIT_EMAIL}
          git config --global user.name ${GIT_USER}
          git clone https://github.com/antrein/prod-yml.git
          cp ./k8s/${{ needs.setup-environment.outputs.BRANCH }}.yml ./prod-yml/${{ env.PROJECT_NAME }}.yml
          cd ./prod-yml
          git add .
          git commit -m "Update Kubernetes YAML file"
          git push https://${GIT_USER}:${GIT_TOKEN}@github.com/antrein/prod-yml.git

  deploy-to-server-aws:
    needs: dockerize-and-push
    if: vars.CLOUD_PLATFORM == 'aws'
    runs-on: ubuntu-latest
    environment: ${{ needs.setup-environment.outputs.BRANCH }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Prepare deployment file
        env: 
          IMAGE_NAME: ${{ needs.setup-environment.outputs.IMAGE_NAME }}
          SHORT_SHA: ${{ needs.setup-environment.outputs.SHORT_SHA }}
        run: |
          sed -i "s|<PROJECT_NAME>|${{ env.PROJECT_NAME }}|g" k8s/${{ needs.setup-environment.outputs.BRANCH }}.yml
          sed -i "s|<IMAGE_NAME>|${{ env.IMAGE_NAME }}|g" k8s/${{ needs.setup-environment.outputs.BRANCH }}.yml
          sed -i "s|<VERSION>|${{ env.SHORT_SHA }}|g" k8s/${{ needs.setup-environment.outputs.BRANCH }}.yml
          sed -i "s|<PORT>|${{ env.PORT }}|g" k8s/${{ needs.setup-environment.outputs.BRANCH }}.yml
          cat k8s/${{ needs.setup-environment.outputs.BRANCH }}.yml

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ vars.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kube config
        run: aws eks update-kubeconfig --name  ${{ env.AWS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/${{ needs.setup-environment.outputs.BRANCH }}.yml

      - name: Push YAML to another GitHub repo
        if: github.ref != 'refs/heads/staging'
        env:
          GIT_USER: reyshazni
          GIT_TOKEN: ${{ vars.GIT_PAT }}
          GIT_EMAIL: reyshazni@gmail.com
        run: |
          git config --global user.email ${GIT_EMAIL}
          git config --global user.name ${GIT_USER}
          git clone https://github.com/antrein/prod-yml.git
          cp ./k8s/${{ needs.setup-environment.outputs.BRANCH }}.yml ./prod-yml/${{ env.PROJECT_NAME }}.yml
          cd ./prod-yml
          git add .
          git commit -m "Update Kubernetes YAML file"
          git push https://${GIT_USER}:${GIT_TOKEN}@github.com/antrein/prod-yml.git

  deploy-to-server-azure:
    needs: dockerize-and-push
    if: vars.CLOUD_PLATFORM == 'azure'
    runs-on: ubuntu-latest
    environment: ${{ needs.setup-environment.outputs.BRANCH }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Prepare deployment file
        env: 
          IMAGE_NAME: ${{ needs.setup-environment.outputs.IMAGE_NAME }}
          SHORT_SHA: ${{ needs.setup-environment.outputs.SHORT_SHA }}
        run: |
          sed -i "s|<PROJECT_NAME>|${{ env.PROJECT_NAME }}|g" k8s/${{ needs.setup-environment.outputs.BRANCH }}.yml
          sed -i "s|<IMAGE_NAME>|${{ env.IMAGE_NAME }}|g" k8s/${{ needs.setup-environment.outputs.BRANCH }}.yml
          sed -i "s|<VERSION>|${{ env.SHORT_SHA }}|g" k8s/${{ needs.setup-environment.outputs.BRANCH }}.yml
          sed -i "s|<PORT>|${{ env.PORT }}|g" k8s/${{ needs.setup-environment.outputs.BRANCH }}.yml
          cat k8s/${{ needs.setup-environment.outputs.BRANCH }}.yml

      - name: Push YAML to another GitHub repo
        if: github.ref != 'refs/heads/staging'
        env:
          GIT_USER: reyshazni
          GIT_TOKEN: ${{ vars.GIT_PAT }}
          GIT_EMAIL: reyshazni@gmail.com
        run: |
          git config --global user.email ${GIT_EMAIL}
          git config --global user.name ${GIT_USER}
          git clone https://github.com/antrein/prod-yml.git
          cp ./k8s/${{ needs.setup-environment.outputs.BRANCH }}.yml ./prod-yml/${{ env.PROJECT_NAME }}.yml
          cd ./prod-yml
          git add .
          git commit -m "Update Kubernetes YAML file"
          git push https://${GIT_USER}:${GIT_TOKEN}@github.com/antrein/prod-yml.git
